#index:
#    path: / 
#    controller: App\Controller\DefaultController::index

#parameters:
#prefix:   /{_locale}
#   controller: App\Controller\AdvertController
#   requirements:
#       _locale: en|fr

index:
    path:       /{_locale}
    controller: App\Controller\AdvertController::home
    requirements:
        _locale: en|fr
translationAction:
    path:       /{_locale}/traduction/12
    controller: App\Controller\AdvertController::translationAction
    requirements:
        _locale: en|fr   